Upgrade to supp lvl
intelsdi-x/snap-plugin-collector-iostat pull request #30
Opened 2017-07-31 12:21 UTC by Armatorix

Summary of changes:
- use of snap plugin library
- update tests
- add licenses

How to verify it:
- make test-all

Testing done:
- make test-all

A picture of a snapping turtle (not required but encouraged):
https://i.ytimg.com/vi/LBSFeJ1WLv4/maxresdefault.jpg

2017-07-31 12:31 UTC, kdembler requested changes

2017-07-31 12:31 UTC, kdembler commented on iostat/iostat.go
>  	"github.com/intelsdi-x/snap/core"
Plugin using lib-go shouldn't import snap

2017-07-31 12:31 UTC, kdembler commented on glide.lock
>  hash: e2b8455d2f47652e91d0350ad7994f4824c6728af81e95c454094734bccbba32
`glide.lock` needs to be updated to reflect changes to dependencies: not importing snap, importing lib-go. I suggest removing both `glide.lock`, `glide.yaml`, clearing glide cache with `$ glide cc` and then going through `$ glide init` to ensure proper dependency list.

2017-07-31 12:31 UTC, kdembler commented on iostat/iostat.go
> +	Version      = 6
Please bump up version

2017-07-31 12:31 UTC, kdembler commented on main.go
> +	pluginName    = "iostat"
Please choose one place to store version and name of plugin - here in `main.go` or in `iostat/iostat.go` and remove the other.

2017-07-31 13:01 UTC, Armatorix commented on main.go
> +	pluginName    = "iostat"
Already deleted from iostat.go.

2017-08-02 12:56 UTC, kdembler approved these changes

2017-08-02 12:56 UTC, kdembler commented on iostat/iostat.go
> +		return nil, nil, fmt.Errorf("Iostat %d.%d.%d version (required >=10.2.0)", version[0], version[1], version[2])
This error message could be a little bit more intuitive (e.g. `This plugin requires iostat in version 10.2.0 or newer (version present={version})`)

2017-08-02 12:56 UTC, kdembler commented on scripts/deps.sh
> +      (cd "${__proj_dir}"  && glide install)
Please remove space

2017-08-03 12:39 UTC, merged